### ISSUE TITLE
So many combinations!

### ISSUE THREAD

**Issue by jchodera** [choderalab/kinase-benchmark#4]
To control the combinatorial expansion of kinases, mutants, protonation states, and inhibitors for this benchmark, what if we used a YAML file to specify what gets mixed up?

Still thinking about the syntax, but maybe something like this:

```
kinases:
  abl:
    - 3UE4
    - 2HYY
  src:
    - 2SRC

kinase_protonation:
  abl:
    - default
    - {318:ASH}
  src:
    - default

mutants:
  abl:
    - WT
    - T315I
  src:
    - WT
    - T338I

inhibitors:
  - bosutinib
  - gefitinib
  - erlotinib
```
